language: java

jdk:
  - oraclejdk8

env:
  global:
    - NODE_VERSION=6
    - THRIFT_VER=0.9.3
    - THRIFT_MD5=88d667a8ae870d5adeca8cb7d6795442

install:
  - nvm install $NODE_VERSION
  - npm install
  - npm prune

script:
  - nvm use $NODE_VERSION
  - npm test
  - ${PWD}/gradlew check

addons:
  apt:
    packages:
      - libevent-dev
      - automake
      - libtool
      - flex
      - bison
      - pkg-config
      - g++
      - libssl-dev
      - html2text

before_install:
  - ${PWD}/scripts/build_thrift.sh
  - export PATH=${PWD}/thrift-${THRIFT_VER}/bin:${PATH}

before_cache:
  # https://docs.travis-ci.com/user/languages/java/#Caching
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - node_modules
    - thrift-${THRIFT_VER}
